name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Create .env file
        run: |
          echo "APP_DEBUG=${{ secrets.APP_DEBUG }}" > .env
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_APP_NAME=${{ secrets.VITE_APP_NAME }}" >> .env
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env
          echo "VITE_PERIODO_ADMISION=${{ secrets.VITE_PERIODO_ADMISION }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  
      - name: Deploy to Server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_FRONTEND_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
